data:
  tables_config:
    source_path: /Volumes/benmackenzie_catalog/rag_benmackenzie/source_docs
    raw_files_table_name: benmackenzie_catalog.rag_benmackenzie.my_agent_app_raw_files_bronze
    parsed_docs_table_name: benmackenzie_catalog.rag_benmackenzie.my_agent_app_parsed_docs_sliver
    chunked_docs_table_name: benmackenzie_catalog.rag_benmackenzie.my_agent_app_chunked_docs_gold

  embedding_config:
    embedding_endpoint_name: databricks-gte-large-en
    embedding_tokenizer:
      tokenizer_model_name: Alibaba-NLP/gte-large-en-v1.5
      tokenizer_source: hugging_face
  
  pipeline_config:
    chunker:
      config:
        chunk_overlap_tokens: 256
        chunk_size_tokens: 1024
      name: langchain_recursive_char

vector_search:
  embedding_endpoint_name: databricks-gte-large-en
  pipeline_type: TRIGGERED

rag_chain:
  databricks_resources:
    llm_endpoint_name: databricks-meta-llama-3-1-70b-instruct
    vector_search_endpoint_name: one-env-shared-endpoint-12
  input_example:
    messages:
    - content: What is RAG?
      role: user
  llm_config:
    llm_parameters:
      max_tokens: 1500
      temperature: 0.01
    llm_system_prompt_template: 'You are an assistant that answers questions. Use the
      following pieces of retrieved context to answer the question. Some pieces of context
      may be irrelevant, in which case you should not use them to form the answer.


      Context: {context}'
  retriever_config:
    chunk_template: 'Passage: {chunk_text}

      '
    data_pipeline_tag: poc
    parameters:
      k: 5
      query_type: ann
    schema:
      chunk_text: chunked_text
      document_uri: path
      primary_key: chunk_id
    vector_search_index: benmackenzie_catalog.rag_benmackenzie.my_agent_app_chunked_docs_gold_index

agent:
  agent_name: simple_chatbot
  uc_model_name: benmackenzie_catalog.simple_chatbot.bmac_technical_pdf_rag_app

eval:
  evaluation_set_fqn: benmackenzie_catalog.rag_benmackenzie.my_agent_app_evaluation_set

mlflow:
  experiment_name: /Users/ben.mackenzie@databricks.com/simple_chatbot_3
